### ISSUE TITLE
Please support configurable idle time

### ISSUE THREAD

**Issue by algernon** [ToyKeeper/Kaleidoscope-LED-Wavepool#1]
First of all, thank you for the amazing effect! I'll have to find some space on my layout to have this on there too.

There is only one thing I found lacking: the ability to (easily) change the time after which the idle animation kicks in. I'd like to be able to  increase it (from 20 to at least 200 frames, but from an user point of view, millisecond based timeout would be easier to understand and work with, I think), or disable the idle animation alltogether (perhaps by setting the timeout to 0?).

Would it be possible to make the plugin support such a setting? (It could still add some randomness by using an idle timeout +/-10% of that of the configured one, for example)

Bonus points if I could use Focus to change the setting too. O:)

**Comment by ToyKeeper** [comment]
Fixed in commit 6e5a10a1c34a61f055f0855dd03cfbc1d99988ab.  Use WavepoolEffect.idle_timeout to set delay in ms before idle animation starts, or 0 to disable the idle animation.
